/** Svenska visningsnamn för FIFA:s engelska lagnamn */
export const TEAM_NAMES_SV: Record<string, string> = {
  Algeria: "Algeriet",
  Argentina: "Argentina",
  Australia: "Australien",
  Austria: "Österrike",
  Belgium: "Belgien",
  "Bosnia and Herzegovina": "Bosnien och Hercegovina",
  Brazil: "Brasilien",
  "Cabo Verde": "Kap Verde",
  Canada: "Kanada",
  Colombia: "Colombia",
  "Congo DR": "DR Kongo",
  Croatia: "Kroatien",
  "Côte d'Ivoire": "Elfenbenskusten",
  Curaçao: "Curaçao",
  Czechia: "Tjeckien",
  Ecuador: "Ecuador",
  Egypt: "Egypten",
  England: "England",
  France: "Frankrike",
  Germany: "Tyskland",
  Ghana: "Ghana",
  Haiti: "Haiti",
  "IR Iran": "Iran",
  Iraq: "Irak",
  Japan: "Japan",
  Jordan: "Jordanien",
  "Korea Republic": "Sydkorea",
  Mexico: "Mexiko",
  Morocco: "Marocko",
  Netherlands: "Nederländerna",
  "New Zealand": "Nya Zeeland",
  Norway: "Norge",
  Panama: "Panama",
  Paraguay: "Paraguay",
  Portugal: "Portugal",
  Qatar: "Qatar",
  "Saudi Arabia": "Saudiarabien",
  Scotland: "Skottland",
  Senegal: "Senegal",
  "South Africa": "Sydafrika",
  Spain: "Spanien",
  Sweden: "Sverige",
  Switzerland: "Schweiz",
  Tunisia: "Tunisien",
  Türkiye: "Turkiet",
  USA: "USA",
  Uruguay: "Uruguay",
  Uzbekistan: "Uzbekistan",
};

export function toSwedishTeamName(englishName: string): string {
  return TEAM_NAMES_SV[englishName] ?? englishName;
}
