// Auto-generated from FIFA — run: npm run sync:fifa
import type { Match } from "@/lib/types";

export const worldCupMatchesFallback: Match[] = [
  {
    "id": "400021443",
    "home": "Mexiko",
    "away": "Sydafrika",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/MEX",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/RSA",
    "kickoff": "11 juni 15:00",
    "kickoffIso": "2026-06-11T13:00:00Z",
    "group": "A",
    "stage": "First Stage",
    "stadium": "Mexico City Stadium",
    "matchNumber": 1
  },
  {
    "id": "400021441",
    "home": "Sydkorea",
    "away": "Tjeckien",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/KOR",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/CZE",
    "kickoff": "11 juni 22:00",
    "kickoffIso": "2026-06-11T20:00:00Z",
    "group": "A",
    "stage": "First Stage",
    "stadium": "Guadalajara Stadium",
    "matchNumber": 2
  },
  {
    "id": "400021449",
    "home": "Kanada",
    "away": "Bosnien och Hercegovina",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/CAN",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/BIH",
    "kickoff": "12 juni 17:00",
    "kickoffIso": "2026-06-12T15:00:00Z",
    "group": "B",
    "stage": "First Stage",
    "stadium": "Toronto Stadium",
    "matchNumber": 3
  },
  {
    "id": "400021458",
    "home": "USA",
    "away": "Paraguay",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/USA",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/PAR",
    "kickoff": "12 juni 20:00",
    "kickoffIso": "2026-06-12T18:00:00Z",
    "group": "D",
    "stage": "First Stage",
    "stadium": "Los Angeles Stadium",
    "matchNumber": 4
  },
  {
    "id": "400021447",
    "home": "Qatar",
    "away": "Schweiz",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/QAT",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/SUI",
    "kickoff": "13 juni 14:00",
    "kickoffIso": "2026-06-13T12:00:00Z",
    "group": "B",
    "stage": "First Stage",
    "stadium": "San Francisco Bay Area Stadium",
    "matchNumber": 8
  },
  {
    "id": "400021456",
    "home": "Brasilien",
    "away": "Marocko",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/BRA",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/MAR",
    "kickoff": "13 juni 20:00",
    "kickoffIso": "2026-06-13T18:00:00Z",
    "group": "C",
    "stage": "First Stage",
    "stadium": "New York/New Jersey Stadium",
    "matchNumber": 7
  },
  {
    "id": "400021453",
    "home": "Haiti",
    "away": "Skottland",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/HAI",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/SCO",
    "kickoff": "13 juni 23:00",
    "kickoffIso": "2026-06-13T21:00:00Z",
    "group": "C",
    "stage": "First Stage",
    "stadium": "Boston Stadium",
    "matchNumber": 5
  },
  {
    "id": "400021463",
    "home": "Australien",
    "away": "Turkiet",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/AUS",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/TUR",
    "kickoff": "13 juni 23:00",
    "kickoffIso": "2026-06-13T21:00:00Z",
    "group": "D",
    "stage": "First Stage",
    "stadium": "BC Place Vancouver",
    "matchNumber": 6
  },
  {
    "id": "400021464",
    "home": "Tyskland",
    "away": "Curaçao",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/GER",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/CUW",
    "kickoff": "14 juni 14:00",
    "kickoffIso": "2026-06-14T12:00:00Z",
    "group": "E",
    "stage": "First Stage",
    "stadium": "Houston Stadium",
    "matchNumber": 10
  },
  {
    "id": "400021470",
    "home": "Nederländerna",
    "away": "Japan",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/NED",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/JPN",
    "kickoff": "14 juni 17:00",
    "kickoffIso": "2026-06-14T15:00:00Z",
    "group": "F",
    "stage": "First Stage",
    "stadium": "Dallas Stadium",
    "matchNumber": 11
  },
  {
    "id": "400021467",
    "home": "Elfenbenskusten",
    "away": "Ecuador",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/CIV",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/ECU",
    "kickoff": "14 juni 21:00",
    "kickoffIso": "2026-06-14T19:00:00Z",
    "group": "E",
    "stage": "First Stage",
    "stadium": "Philadelphia Stadium",
    "matchNumber": 9
  },
  {
    "id": "400021474",
    "home": "Sverige",
    "away": "Tunisien",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/SWE",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/TUN",
    "kickoff": "14 juni 22:00",
    "kickoffIso": "2026-06-14T20:00:00Z",
    "group": "F",
    "stage": "First Stage",
    "stadium": "Monterrey Stadium",
    "matchNumber": 12
  },
  {
    "id": "400021482",
    "home": "Spanien",
    "away": "Kap Verde",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/ESP",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/CPV",
    "kickoff": "15 juni 14:00",
    "kickoffIso": "2026-06-15T12:00:00Z",
    "group": "H",
    "stage": "First Stage",
    "stadium": "Atlanta Stadium",
    "matchNumber": 14
  },
  {
    "id": "400021478",
    "home": "Belgien",
    "away": "Egypten",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/BEL",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/EGY",
    "kickoff": "15 juni 14:00",
    "kickoffIso": "2026-06-15T12:00:00Z",
    "group": "G",
    "stage": "First Stage",
    "stadium": "Seattle Stadium",
    "matchNumber": 16
  },
  {
    "id": "400021486",
    "home": "Saudiarabien",
    "away": "Uruguay",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/KSA",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/URU",
    "kickoff": "15 juni 20:00",
    "kickoffIso": "2026-06-15T18:00:00Z",
    "group": "H",
    "stage": "First Stage",
    "stadium": "Miami Stadium",
    "matchNumber": 13
  },
  {
    "id": "400021476",
    "home": "Iran",
    "away": "Nya Zeeland",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/IRN",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/NZL",
    "kickoff": "15 juni 20:00",
    "kickoffIso": "2026-06-15T18:00:00Z",
    "group": "G",
    "stage": "First Stage",
    "stadium": "Los Angeles Stadium",
    "matchNumber": 15
  },
  {
    "id": "400021490",
    "home": "Frankrike",
    "away": "Senegal",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/FRA",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/SEN",
    "kickoff": "16 juni 17:00",
    "kickoffIso": "2026-06-16T15:00:00Z",
    "group": "I",
    "stage": "First Stage",
    "stadium": "New York/New Jersey Stadium",
    "matchNumber": 17
  },
  {
    "id": "400021488",
    "home": "Irak",
    "away": "Norge",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/IRQ",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/NOR",
    "kickoff": "16 juni 20:00",
    "kickoffIso": "2026-06-16T18:00:00Z",
    "group": "I",
    "stage": "First Stage",
    "stadium": "Boston Stadium",
    "matchNumber": 18
  },
  {
    "id": "400021496",
    "home": "Argentina",
    "away": "Algeriet",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/ARG",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/ALG",
    "kickoff": "16 juni 22:00",
    "kickoffIso": "2026-06-16T20:00:00Z",
    "group": "J",
    "stage": "First Stage",
    "stadium": "Kansas City Stadium",
    "matchNumber": 19
  },
  {
    "id": "400021498",
    "home": "Österrike",
    "away": "Jordanien",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/AUT",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/JOR",
    "kickoff": "16 juni 23:00",
    "kickoffIso": "2026-06-16T21:00:00Z",
    "group": "J",
    "stage": "First Stage",
    "stadium": "San Francisco Bay Area Stadium",
    "matchNumber": 20
  },
  {
    "id": "400021502",
    "home": "Portugal",
    "away": "DR Kongo",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/POR",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/COD",
    "kickoff": "17 juni 14:00",
    "kickoffIso": "2026-06-17T12:00:00Z",
    "group": "K",
    "stage": "First Stage",
    "stadium": "Houston Stadium",
    "matchNumber": 23
  },
  {
    "id": "400021507",
    "home": "England",
    "away": "Kroatien",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/ENG",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/CRO",
    "kickoff": "17 juni 17:00",
    "kickoffIso": "2026-06-17T15:00:00Z",
    "group": "L",
    "stage": "First Stage",
    "stadium": "Dallas Stadium",
    "matchNumber": 22
  },
  {
    "id": "400021510",
    "home": "Ghana",
    "away": "Panama",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/GHA",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/PAN",
    "kickoff": "17 juni 21:00",
    "kickoffIso": "2026-06-17T19:00:00Z",
    "group": "L",
    "stage": "First Stage",
    "stadium": "Toronto Stadium",
    "matchNumber": 21
  },
  {
    "id": "400021504",
    "home": "Uzbekistan",
    "away": "Colombia",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/UZB",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/COL",
    "kickoff": "17 juni 22:00",
    "kickoffIso": "2026-06-17T20:00:00Z",
    "group": "K",
    "stage": "First Stage",
    "stadium": "Mexico City Stadium",
    "matchNumber": 24
  },
  {
    "id": "400021440",
    "home": "Tjeckien",
    "away": "Sydafrika",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/CZE",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/RSA",
    "kickoff": "18 juni 14:00",
    "kickoffIso": "2026-06-18T12:00:00Z",
    "group": "A",
    "stage": "First Stage",
    "stadium": "Atlanta Stadium",
    "matchNumber": 25
  },
  {
    "id": "400021446",
    "home": "Schweiz",
    "away": "Bosnien och Hercegovina",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/SUI",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/BIH",
    "kickoff": "18 juni 14:00",
    "kickoffIso": "2026-06-18T12:00:00Z",
    "group": "B",
    "stage": "First Stage",
    "stadium": "Los Angeles Stadium",
    "matchNumber": 26
  },
  {
    "id": "400021450",
    "home": "Kanada",
    "away": "Qatar",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/CAN",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/QAT",
    "kickoff": "18 juni 17:00",
    "kickoffIso": "2026-06-18T15:00:00Z",
    "group": "B",
    "stage": "First Stage",
    "stadium": "BC Place Vancouver",
    "matchNumber": 27
  },
  {
    "id": "400021442",
    "home": "Mexiko",
    "away": "Sydkorea",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/MEX",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/KOR",
    "kickoff": "18 juni 21:00",
    "kickoffIso": "2026-06-18T19:00:00Z",
    "group": "A",
    "stage": "First Stage",
    "stadium": "Guadalajara Stadium",
    "matchNumber": 28
  },
  {
    "id": "400021462",
    "home": "USA",
    "away": "Australien",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/USA",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/AUS",
    "kickoff": "19 juni 14:00",
    "kickoffIso": "2026-06-19T12:00:00Z",
    "group": "D",
    "stage": "First Stage",
    "stadium": "Seattle Stadium",
    "matchNumber": 32
  },
  {
    "id": "400021454",
    "home": "Skottland",
    "away": "Marocko",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/SCO",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/MAR",
    "kickoff": "19 juni 20:00",
    "kickoffIso": "2026-06-19T18:00:00Z",
    "group": "C",
    "stage": "First Stage",
    "stadium": "Boston Stadium",
    "matchNumber": 30
  },
  {
    "id": "400021460",
    "home": "Turkiet",
    "away": "Paraguay",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/TUR",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/PAR",
    "kickoff": "19 juni 22:00",
    "kickoffIso": "2026-06-19T20:00:00Z",
    "group": "D",
    "stage": "First Stage",
    "stadium": "San Francisco Bay Area Stadium",
    "matchNumber": 31
  },
  {
    "id": "400021457",
    "home": "Brasilien",
    "away": "Haiti",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/BRA",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/HAI",
    "kickoff": "19 juni 22:30",
    "kickoffIso": "2026-06-19T20:30:00Z",
    "group": "C",
    "stage": "First Stage",
    "stadium": "Philadelphia Stadium",
    "matchNumber": 29
  },
  {
    "id": "400021472",
    "home": "Nederländerna",
    "away": "Sverige",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/NED",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/SWE",
    "kickoff": "20 juni 14:00",
    "kickoffIso": "2026-06-20T12:00:00Z",
    "group": "F",
    "stage": "First Stage",
    "stadium": "Houston Stadium",
    "matchNumber": 35
  },
  {
    "id": "400021469",
    "home": "Tyskland",
    "away": "Elfenbenskusten",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/GER",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/CIV",
    "kickoff": "20 juni 18:00",
    "kickoffIso": "2026-06-20T16:00:00Z",
    "group": "E",
    "stage": "First Stage",
    "stadium": "Toronto Stadium",
    "matchNumber": 33
  },
  {
    "id": "400021465",
    "home": "Ecuador",
    "away": "Curaçao",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/ECU",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/CUW",
    "kickoff": "20 juni 21:00",
    "kickoffIso": "2026-06-20T19:00:00Z",
    "group": "E",
    "stage": "First Stage",
    "stadium": "Kansas City Stadium",
    "matchNumber": 34
  },
  {
    "id": "400021475",
    "home": "Tunisien",
    "away": "Japan",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/TUN",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/JPN",
    "kickoff": "21 juni 00:00",
    "kickoffIso": "2026-06-20T22:00:00Z",
    "group": "F",
    "stage": "First Stage",
    "stadium": "Monterrey Stadium",
    "matchNumber": 36
  },
  {
    "id": "400021483",
    "home": "Spanien",
    "away": "Saudiarabien",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/ESP",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/KSA",
    "kickoff": "21 juni 14:00",
    "kickoffIso": "2026-06-21T12:00:00Z",
    "group": "H",
    "stage": "First Stage",
    "stadium": "Atlanta Stadium",
    "matchNumber": 38
  },
  {
    "id": "400021477",
    "home": "Belgien",
    "away": "Iran",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/BEL",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/IRN",
    "kickoff": "21 juni 14:00",
    "kickoffIso": "2026-06-21T12:00:00Z",
    "group": "G",
    "stage": "First Stage",
    "stadium": "Los Angeles Stadium",
    "matchNumber": 39
  },
  {
    "id": "400021487",
    "home": "Uruguay",
    "away": "Kap Verde",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/URU",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/CPV",
    "kickoff": "21 juni 20:00",
    "kickoffIso": "2026-06-21T18:00:00Z",
    "group": "H",
    "stage": "First Stage",
    "stadium": "Miami Stadium",
    "matchNumber": 37
  },
  {
    "id": "400021480",
    "home": "Nya Zeeland",
    "away": "Egypten",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/NZL",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/EGY",
    "kickoff": "21 juni 20:00",
    "kickoffIso": "2026-06-21T18:00:00Z",
    "group": "G",
    "stage": "First Stage",
    "stadium": "BC Place Vancouver",
    "matchNumber": 40
  },
  {
    "id": "400021494",
    "home": "Argentina",
    "away": "Österrike",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/ARG",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/AUT",
    "kickoff": "22 juni 14:00",
    "kickoffIso": "2026-06-22T12:00:00Z",
    "group": "J",
    "stage": "First Stage",
    "stadium": "Dallas Stadium",
    "matchNumber": 43
  },
  {
    "id": "400021492",
    "home": "Frankrike",
    "away": "Irak",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/FRA",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/IRQ",
    "kickoff": "22 juni 19:00",
    "kickoffIso": "2026-06-22T17:00:00Z",
    "group": "I",
    "stage": "First Stage",
    "stadium": "Philadelphia Stadium",
    "matchNumber": 42
  },
  {
    "id": "400021491",
    "home": "Norge",
    "away": "Senegal",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/NOR",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/SEN",
    "kickoff": "22 juni 22:00",
    "kickoffIso": "2026-06-22T20:00:00Z",
    "group": "I",
    "stage": "First Stage",
    "stadium": "New York/New Jersey Stadium",
    "matchNumber": 41
  },
  {
    "id": "400021499",
    "home": "Jordanien",
    "away": "Algeriet",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/JOR",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/ALG",
    "kickoff": "22 juni 22:00",
    "kickoffIso": "2026-06-22T20:00:00Z",
    "group": "J",
    "stage": "First Stage",
    "stadium": "San Francisco Bay Area Stadium",
    "matchNumber": 44
  },
  {
    "id": "400021503",
    "home": "Portugal",
    "away": "Uzbekistan",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/POR",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/UZB",
    "kickoff": "23 juni 14:00",
    "kickoffIso": "2026-06-23T12:00:00Z",
    "group": "K",
    "stage": "First Stage",
    "stadium": "Houston Stadium",
    "matchNumber": 47
  },
  {
    "id": "400021506",
    "home": "England",
    "away": "Ghana",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/ENG",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/GHA",
    "kickoff": "23 juni 18:00",
    "kickoffIso": "2026-06-23T16:00:00Z",
    "group": "L",
    "stage": "First Stage",
    "stadium": "Boston Stadium",
    "matchNumber": 45
  },
  {
    "id": "400021511",
    "home": "Panama",
    "away": "Kroatien",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/PAN",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/CRO",
    "kickoff": "23 juni 21:00",
    "kickoffIso": "2026-06-23T19:00:00Z",
    "group": "L",
    "stage": "First Stage",
    "stadium": "Toronto Stadium",
    "matchNumber": 46
  },
  {
    "id": "400021501",
    "home": "Colombia",
    "away": "DR Kongo",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/COL",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/COD",
    "kickoff": "23 juni 22:00",
    "kickoffIso": "2026-06-23T20:00:00Z",
    "group": "K",
    "stage": "First Stage",
    "stadium": "Guadalajara Stadium",
    "matchNumber": 48
  },
  {
    "id": "400021451",
    "home": "Schweiz",
    "away": "Kanada",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/SUI",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/CAN",
    "kickoff": "24 juni 14:00",
    "kickoffIso": "2026-06-24T12:00:00Z",
    "group": "B",
    "stage": "First Stage",
    "stadium": "BC Place Vancouver",
    "matchNumber": 51
  },
  {
    "id": "400021448",
    "home": "Bosnien och Hercegovina",
    "away": "Qatar",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/BIH",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/QAT",
    "kickoff": "24 juni 14:00",
    "kickoffIso": "2026-06-24T12:00:00Z",
    "group": "B",
    "stage": "First Stage",
    "stadium": "Seattle Stadium",
    "matchNumber": 52
  },
  {
    "id": "400021455",
    "home": "Skottland",
    "away": "Brasilien",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/SCO",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/BRA",
    "kickoff": "24 juni 20:00",
    "kickoffIso": "2026-06-24T18:00:00Z",
    "group": "C",
    "stage": "First Stage",
    "stadium": "Miami Stadium",
    "matchNumber": 49
  },
  {
    "id": "400021452",
    "home": "Marocko",
    "away": "Haiti",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/MAR",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/HAI",
    "kickoff": "24 juni 20:00",
    "kickoffIso": "2026-06-24T18:00:00Z",
    "group": "C",
    "stage": "First Stage",
    "stadium": "Atlanta Stadium",
    "matchNumber": 50
  },
  {
    "id": "400021444",
    "home": "Tjeckien",
    "away": "Mexiko",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/CZE",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/MEX",
    "kickoff": "24 juni 21:00",
    "kickoffIso": "2026-06-24T19:00:00Z",
    "group": "A",
    "stage": "First Stage",
    "stadium": "Mexico City Stadium",
    "matchNumber": 53
  },
  {
    "id": "400021445",
    "home": "Sydafrika",
    "away": "Sydkorea",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/RSA",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/KOR",
    "kickoff": "24 juni 21:00",
    "kickoffIso": "2026-06-24T19:00:00Z",
    "group": "A",
    "stage": "First Stage",
    "stadium": "Monterrey Stadium",
    "matchNumber": 54
  },
  {
    "id": "400021468",
    "home": "Curaçao",
    "away": "Elfenbenskusten",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/CUW",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/CIV",
    "kickoff": "25 juni 18:00",
    "kickoffIso": "2026-06-25T16:00:00Z",
    "group": "E",
    "stage": "First Stage",
    "stadium": "Philadelphia Stadium",
    "matchNumber": 55
  },
  {
    "id": "400021466",
    "home": "Ecuador",
    "away": "Tyskland",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/ECU",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/GER",
    "kickoff": "25 juni 18:00",
    "kickoffIso": "2026-06-25T16:00:00Z",
    "group": "E",
    "stage": "First Stage",
    "stadium": "New York/New Jersey Stadium",
    "matchNumber": 56
  },
  {
    "id": "400021471",
    "home": "Japan",
    "away": "Sverige",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/JPN",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/SWE",
    "kickoff": "25 juni 20:00",
    "kickoffIso": "2026-06-25T18:00:00Z",
    "group": "F",
    "stage": "First Stage",
    "stadium": "Dallas Stadium",
    "matchNumber": 57
  },
  {
    "id": "400021473",
    "home": "Tunisien",
    "away": "Nederländerna",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/TUN",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/NED",
    "kickoff": "25 juni 20:00",
    "kickoffIso": "2026-06-25T18:00:00Z",
    "group": "F",
    "stage": "First Stage",
    "stadium": "Kansas City Stadium",
    "matchNumber": 58
  },
  {
    "id": "400021459",
    "home": "Turkiet",
    "away": "USA",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/TUR",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/USA",
    "kickoff": "25 juni 21:00",
    "kickoffIso": "2026-06-25T19:00:00Z",
    "group": "D",
    "stage": "First Stage",
    "stadium": "Los Angeles Stadium",
    "matchNumber": 59
  },
  {
    "id": "400021461",
    "home": "Paraguay",
    "away": "Australien",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/PAR",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/AUS",
    "kickoff": "25 juni 21:00",
    "kickoffIso": "2026-06-25T19:00:00Z",
    "group": "D",
    "stage": "First Stage",
    "stadium": "San Francisco Bay Area Stadium",
    "matchNumber": 60
  },
  {
    "id": "400021489",
    "home": "Norge",
    "away": "Frankrike",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/NOR",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/FRA",
    "kickoff": "26 juni 17:00",
    "kickoffIso": "2026-06-26T15:00:00Z",
    "group": "I",
    "stage": "First Stage",
    "stadium": "Boston Stadium",
    "matchNumber": 61
  },
  {
    "id": "400021493",
    "home": "Senegal",
    "away": "Irak",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/SEN",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/IRQ",
    "kickoff": "26 juni 17:00",
    "kickoffIso": "2026-06-26T15:00:00Z",
    "group": "I",
    "stage": "First Stage",
    "stadium": "Toronto Stadium",
    "matchNumber": 62
  },
  {
    "id": "400021484",
    "home": "Uruguay",
    "away": "Spanien",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/URU",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/ESP",
    "kickoff": "26 juni 20:00",
    "kickoffIso": "2026-06-26T18:00:00Z",
    "group": "H",
    "stage": "First Stage",
    "stadium": "Guadalajara Stadium",
    "matchNumber": 66
  },
  {
    "id": "400021485",
    "home": "Kap Verde",
    "away": "Saudiarabien",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/CPV",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/KSA",
    "kickoff": "26 juni 21:00",
    "kickoffIso": "2026-06-26T19:00:00Z",
    "group": "H",
    "stage": "First Stage",
    "stadium": "Houston Stadium",
    "matchNumber": 65
  },
  {
    "id": "400021479",
    "home": "Egypten",
    "away": "Iran",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/EGY",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/IRN",
    "kickoff": "26 juni 22:00",
    "kickoffIso": "2026-06-26T20:00:00Z",
    "group": "G",
    "stage": "First Stage",
    "stadium": "Seattle Stadium",
    "matchNumber": 63
  },
  {
    "id": "400021481",
    "home": "Nya Zeeland",
    "away": "Belgien",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/NZL",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/BEL",
    "kickoff": "26 juni 22:00",
    "kickoffIso": "2026-06-26T20:00:00Z",
    "group": "G",
    "stage": "First Stage",
    "stadium": "BC Place Vancouver",
    "matchNumber": 64
  },
  {
    "id": "400021508",
    "home": "Panama",
    "away": "England",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/PAN",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/ENG",
    "kickoff": "27 juni 19:00",
    "kickoffIso": "2026-06-27T17:00:00Z",
    "group": "L",
    "stage": "First Stage",
    "stadium": "New York/New Jersey Stadium",
    "matchNumber": 67
  },
  {
    "id": "400021509",
    "home": "Kroatien",
    "away": "Ghana",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/CRO",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/GHA",
    "kickoff": "27 juni 19:00",
    "kickoffIso": "2026-06-27T17:00:00Z",
    "group": "L",
    "stage": "First Stage",
    "stadium": "Philadelphia Stadium",
    "matchNumber": 68
  },
  {
    "id": "400021505",
    "home": "Colombia",
    "away": "Portugal",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/COL",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/POR",
    "kickoff": "27 juni 21:30",
    "kickoffIso": "2026-06-27T19:30:00Z",
    "group": "K",
    "stage": "First Stage",
    "stadium": "Miami Stadium",
    "matchNumber": 71
  },
  {
    "id": "400021500",
    "home": "DR Kongo",
    "away": "Uzbekistan",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/COD",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/UZB",
    "kickoff": "27 juni 21:30",
    "kickoffIso": "2026-06-27T19:30:00Z",
    "group": "K",
    "stage": "First Stage",
    "stadium": "Atlanta Stadium",
    "matchNumber": 72
  },
  {
    "id": "400021497",
    "home": "Algeriet",
    "away": "Österrike",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/ALG",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/AUT",
    "kickoff": "27 juni 23:00",
    "kickoffIso": "2026-06-27T21:00:00Z",
    "group": "J",
    "stage": "First Stage",
    "stadium": "Kansas City Stadium",
    "matchNumber": 69
  },
  {
    "id": "400021495",
    "home": "Jordanien",
    "away": "Argentina",
    "homeFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/JOR",
    "awayFlag": "https://api.fifa.com/api/v3/picture/flags-sq-4/ARG",
    "kickoff": "27 juni 23:00",
    "kickoffIso": "2026-06-27T21:00:00Z",
    "group": "J",
    "stage": "First Stage",
    "stadium": "Dallas Stadium",
    "matchNumber": 70
  }
];
